tap "homebrew/bundle"
brew "autoconf"
brew "automake"
brew "bison"
brew "glib"
brew "cairo"
brew "libtool"
brew "gdk-pixbuf"
brew "git"
brew "readline"
brew "gobject-introspection"
brew "harfbuzz"
brew "libffi"
brew "libxml2"
brew "libxslt"
brew "libyaml"
brew "ncurses"
brew "openjdk"
brew "openssl@3", link: false
brew "pango"
brew "pyenv"
brew "watchman"
brew "wget"
brew "zsh"
brew "libpq"
cask "chromium"
cask "flameshot"
cask "ngrok"
cask "discord"
cask "dbeaver-community"
cask "notion"
cask "obsidian"
cask "arc"
cask "skype"
cask "visual-studio-code"
cask "figma"
cask "tiles"
cask "spotify"
cask "libreoffice"
cask "docker"

# ---- Terminal + runtime dos agentes ----
cask "ghostty"          # terminal (config em config/ghostty)
cask "nikitabobko/tap/aerospace" # window manager (config em config/aerospace)
# herdr nao esta no brew: curl -fsSL https://herdr.dev/install.sh | sh

# ---- Shell (dependencias do .zshrc) ----
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "eza"
brew "bat"
brew "fzf"
